rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount KomachiHeartbeat::Engine => '/ops'

  root 'homes#show'

  resources :branches, only: %i[show] do
    resources :assessments, only: %i[new create] do
      get :success, on: :collection
    end
  end
  resources :sale_reviews, only: %i[show]
  resources :cities, only: %i[show]
end

rails/app/models/branch.rb
# frozen_string_literal: true

require 'csv'

class Branch < ApplicationRecord
  belongs_to :company
  belongs_to :city
  has_many :branch_city_assessables, dependent: :destroy
  has_many :assessable_cities, through: :branch_city_assessables, source: :city
  has_many :sale_reviews, dependent: :destroy
  has_many :raw_sale_reviews, dependent: :destroy

  def avg_service_satisfaction
    sale_reviews.average(:service_satisfaction)
  end

  def avg_sale_price_satisfaction
    sale_reviews.average(:sale_price_satisfaction)
  end

  def avg_speed_satisfaction
    sale_reviews.average(:speed_satisfaction)
  end

  def avg_satisfactions
    return nil if avg_service_satisfaction.nil? || avg_sale_price_satisfaction.nil? || avg_speed_satisfaction.nil?

    (avg_service_satisfaction + avg_sale_price_satisfaction + avg_speed_satisfaction) / 3.0
  end

  def company_branch_name
    name.present? ? "#{company.name} #{name}" : company.name
  end

  def self.create_branches_from_csv(path)
    data = CSV.read(path)[2..]
    data.each_with_index do |row, idx|
      # Companyの作成/更新
      company = Company.find_or_initialize_by(id: row[2])
      company.assign_attributes(name: row[0])
      company.save!

      # 店舗が属する市を取得
      Prefecture.find_by(name: row[6])
      city = City.find_by(name: row[7])

      branch = find_or_initialize_by(id: row[3])
      branch.assign_attributes(
        name: row[1] || '',
        company_id: row[2],
        logo_url: row[4],
        post_number: row[5],
        city_id: city.id,
        address: row[8],
        phone: row[9],
        fax_number: row[10],
        business_hours: row[11],
        regular_holiday: row[12],
        catchphrase: row[13],
        introduction: row[14]
      )
      branch.save!

      # 査定可能エリアを登録
      row[15].split(',').each do |assessable_city_id|
        branch.assessable_cities << City.find(assessable_city_id) \
          if branch.assessable_cities.pluck(:id).exclude?(assessable_city_id.to_i)
      end

      # 100行ごとに出力
      Logger.new($stdout).debug "Line #{idx} OK" if (idx % 100).zero?
    end
  end
end

rails/app/controllers/branches_controller.rb
# frozen_string_literal: true

class BranchesController < ApplicationController
  def show
    @branch = Branch.find(params[:id])
    @sale_reviews = @branch.sale_reviews.page(params[:page])
    @score_range = 1..5
    @scores = {
      service: @branch.avg_service_satisfaction,
      speed: @branch.avg_speed_satisfaction,
      price: @branch.avg_sale_price_satisfaction
    }
  end
end

rails/app/views/branches/_description.html.haml
%h3.h6.fw-bold.mb-3 #{branch.company.name}について
%ul.list-unstyled
  %li 企業名：#{branch.company.name}
  %li 郵便番号：#{branch.post_number}
  %li 住所：#{branch.city.prefecture.name}#{branch.city.name}#{branch.address}
  %li 電話番号：#{branch.phone}
  %li FAX：#{branch.fax_number}
  %li 営業時間：#{branch.business_hours}
  %li 定休日：#{branch.regular_holiday}

rails/app/views/branches/_display_stars.html.haml
%span.star
  - range.each do |num|
    - if sale_score.floor >= num
      &#9733;
    - else 
      &#9734;

rails/app/views/branches/show.html.haml
- content_for(:breadcrumbs) do
  = render 'application/breadcrumbs', args: { city: @branch.city, branch: @branch }
- content_for(:title, @branch.company_branch_name)
- content_for(:description, "#{@branch.company_branch_name}の査定依頼や売却申し込みをした方々の率直な声をご覧いただけるページです。信頼性の高い不動産会社を選ぶための貴重な情報源として、#{@branch.company_branch_name}の評価や口コミをご確認ください。過去の取引経験から得られるリアルな意見が、安心して取引する際の参考になることでしょう。お客様の満足度や対応力、プロフェッショナリズムに関する評判など、様々な観点から#{@branch.company_branch_name}を評価している声をお届けします。")
- content_for(:meta_keywords, @branch.company_branch_name)

- if @branch.sale_reviews.empty?
  - content_for(:noindex, true)

.branch-wrapper.centered-content
  %h1.text-center= @branch.company_branch_name
  .row.mt-5.d-flex.justify-content-between
    .col
      %h2.h4.mb-3 #{@branch.catchphrase}
      %p.text-muted #{@branch.introduction}
    
    .col-3.d-flex.justify-content-end
      %img.img-fluid{ alt: "ロゴ画像", src: "#{@branch.logo_url}" }/

  .row.mt-5.pb-5
    - if @branch.sale_reviews.present?
      .col.text-center.position-relative.graphics
        - sale_score = number_with_precision(@branch.avg_satisfactions, precision: 1)
        .d-flex.align-items-center.justify-content-center.canvas-wrapper
          %canvas#branchRadarGraph{ data: { scores: @scores.to_json } }
          %p.position-absolute.score-point= sale_score
        %p.d-flex.justify-content-center.m-0
          %p.fw-bold.m-0 売却スコア
          %div= render 'branches/display_stars', sale_score: sale_score.to_i, range: @score_range
          .average-sale-score= sale_score

    .col.branch-info
      = render 'branches/description', branch: @branch

  .row.mt-5
    %h3.h6.mb-3.fw-bold #{@branch.company.name}で売却したひとの不動産会社についての口コミ（平均評価★#{@branch.avg_service_satisfaction}）
    
    - @sale_reviews.each do |review|
      = link_to sale_review_path(review), class: "link-card" do 
        .card.mb-3
          .card-body
            %h4.h6.fw-bold.card-title #{review.title}：★#{review.service_satisfaction}
            .card-text.mt-2 #{review.service_satisfaction_reason}
            .mt-3.text-body-tertiary.d-flex.justify-content-end 成約価格 #{format_price review.final_sale_price}（#{review.city.prefecture_city_name}・#{year_month_description(review.sale_period)}に売却）

  %div=paginate @sale_reviews
  .row.pt-5.d-flex.justify-content-center
    = link_to new_branch_assessment_path(@branch), class: "btn btn-blue text-center w-auto btn--link" do
      査定依頼をする

%script{ src: "https://cdn.jsdelivr.net/npm/chart.js" }