rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount KomachiHeartbeat::Engine => '/ops'

  root 'homes#show'

  resources :branches, only: %i[show] do
    resources :assessments, only: %i[new create] do
      get :success, on: :collection
    end
  end
  resources :sale_reviews, only: %i[show]
  resources :cities, only: %i[show]
end

rails/app/models/assessment.rb
# frozen_string_literal: true

class Assessment < ApplicationRecord
  belongs_to :assessment_user
  belongs_to :branch
  belongs_to :city

  with_options presence: true do
    validates :property_type
    validates :property_room_plan
    validates :property_constructed_year
  end

  with_options numericality: true do
    validates :property_exclusive_area
    validates :property_land_area
    validates :property_building_area
  end

  validates :property_constructed_year,
            numericality: { allow_blank: true, only_integer: true, greater_than_or_equal_to: 1925,
                            less_than_or_equal_to: 2016 }
  validate :validate_property_exclusive_area
  validate :validate_property_land_area
  validate :validate_property_building_area

  enum property_type: {
    apartment: 1,
    house: 2,
    land: 3
  }, _prefix: true

  enum property_building_area_unit: {
    square_meter: 1,
    tsubo: 2
  }, _prefix: true

  enum property_room_plan: {
    one_room: 1,
    one_k_dk: 2,
    one_lk_ldk: 3,
    two_k_dk: 4,
    two_lk_ldk: 5,
    three_k_dk: 6,
    three_lk_ldk: 7,
    four_k_dk: 8,
    foour_lk_ldk: 9,
    five_k_dk: 10,
    five_lk_ldk: 11,
    six_k_dk: 12,
    six_lk_ldk_or_more: 13
  }, _prefix: true

  def validate_property_exclusive_area
    return unless property_type == 'apartment' && (property_exclusive_area.nil? || property_exclusive_area.zero?)

    errors.add(:property_exclusive_area, 'を指定してください')
  end

  def validate_property_land_area
    return unless %w[house land].include?(property_type) && (property_land_area.nil? || property_land_area.zero?)

    errors.add(:property_land_area, 'を指定してください')
  end

  def validate_property_building_area
    return unless property_type == 'house' && (property_building_area.nil? || property_building_area.zero?)

    errors.add(:property_building_area, 'を指定してください')
  end
end

rails/app/controllers/assessments_controller.rb
# frozen_string_literal: true

class AssessmentsController < ApplicationController
  before_action :require_branch

  def new
    @assessment_user = AssessmentUser.new
    @assessment = Assessment.new
    @prefecture = Prefecture.new
  end

  def create
    @assessment_user = AssessmentUser.find_or_initialize_by(assessment_user_params)
    @assessment = @assessment_user.assessments.new(assessment_params)
    @assessment.branch_id = @branch.id

    return render 'new', status: :bad_request \
      unless save_assessment_user_and_assessment(@assessment_user, @assessment)

    response = create_miniul_assessment(@assessment_user, @assessment)

    if response.code == '200'
      redirect_to success_branch_assessments_path(@branch)
    else
      redirect_to new_branch_assessment_path(@branch), alert: I18n.t('messages.assessment.miniul_api_fail')
    end
  end

  def succsess; end

  private

  def require_branch
    @branch = Branch.find(params[:branch_id])
  end

  def assessment_user_params
    params.require(:assessment_user).permit(:first_name, :last_name, :first_name_kana, :last_name_kana,
                                            :email, :tel)
  end

  def assessment_params
    params[:assessment_user].require(:assessment).permit(:branch_id,
                                                         :city_id,
                                                         :property_address,
                                                         :property_type,
                                                         :property_exclusive_area,
                                                         :property_land_area,
                                                         :property_building_area,
                                                         :property_room_plan,
                                                         :property_constructed_year)
  end

  def save_assessment_user_and_assessment(user, assessment)
    return false unless user.valid? && assessment.valid?

    ActiveRecord::Base.transaction do
      @assessment_user.save!
      @assessment.save!
    end
  end

  def create_miniul_assessment(assessment_user, assessment)
    Miniul.create_assessment({
                               branch_id: assessment.branch.id,
                               property_city: assessment.city.id,
                               property_address: assessment.property_address,
                               property_type: Assessment.property_types[assessment.property_type],
                               property_exclusive_area: assessment.property_exclusive_area,
                               property_land_area: assessment.property_land_area,
                               property_building_area: assessment.property_building_area,
                               property_room_plan: Assessment.property_room_plans[assessment.property_room_plan],
                               property_constructed_year: assessment.property_constructed_year,
                               user_email: assessment_user.email,
                               user_name: "#{assessment_user.last_name} #{assessment_user.first_name}",
                               user_name_kana: "#{assessment_user.last_name_kana} #{assessment_user.first_name_kana}",
                               user_tel: assessment_user.tel
                             })
  end
end

rails/app/views/assessments/new.html.haml
- content_for(:title, "査定依頼フォーム")
- content_for(:breadcrumbs) do
  = render 'application/breadcrumbs', args: { city: @branch.city, branch: @branch }
- content_for(:noindex, true)

%h1.page_title.text-center
  査定依頼フォーム
%h2.text-center.h3
  = @branch.company_branch_name
%p.text-center
  査定可能なエリア:
  - if @branch.assessable_cities.length < 4
    = @branch.assessable_cities.map(&:prefecture_city_name).join(', ')
  - else
    = "#{@branch.assessable_cities[...3].map(&:prefecture_city_name).join(', ')}...他"
    
= form_with(model: @assessment_user, url: branch_assessments_path, class: 'mt-5 mb-5 centered-content', method: :post) do |f|
  - if @assessment_user&.errors&.any?
    - @assessment_user.errors.delete(:assessments)
    - @assessment_user.errors.full_messages.each do |msg|
      .text-danger=msg
  - if @assessment&.errors&.any?
    - @assessment.errors.full_messages.each do |msg|
      .text-danger=msg
  
  %label.row.mt-3
    .col-4
      お名前
      %span.text-danger *
    .col-4= f.text_field :last_name, class: 'form-control', placeholder: "田中", required: true
    .col-4= f.text_field :first_name, class: 'form-control', placeholder: "太郎", required: true
  
  %label.row.mt-3
    .col-4
      フリガナ
      %span.text-danger *
    .col-4= f.text_field :last_name_kana, class: 'form-control', placeholder: "タナカ", required: true
    .col-4= f.text_field :first_name_kana, class: 'form-control', placeholder: "タロウ", required: true

  %label.row.mt-3
    .col-4
      メールアドレス
      %span.text-danger *
    .col-8= f.text_field :email, class: 'form-control', placeholder: 'beteran@example.com', required: true

  %label.row.mt-3
    .col-4
      電話番号
      %span.text-danger *
    .col-8= f.text_field :tel, class: 'form-control', placeholder: 'ハイフンなしで入力してください', required: true

  = f.fields_for :assessment, @assessment do |assessment_f|
    %label.row.mt-3
      .col-4
        都道府県・市区町村
        %span.text-danger *
      .col-8= assessment_f.collection_select :city_id, @branch.assessable_cities, :id, :prefecture_city_name_with_space, {}, class: 'form-select', required: true

    %label.row.mt-3
      .col-4
        物件住所（市区町村以下）
        %span.text-danger *
      .col-8= assessment_f.text_field :property_address, class: 'form-control', required: true

    %label.row.mt-3
      .col-4
        物件種別
        %span.text-danger *
      .col-8= assessment_f.select :property_type, Assessment.property_types_i18n.invert, {}, class: 'form-select', required: true

    %label.row.mt-3.property-exclusive-area
      .col-4
        専有面積(m
        %sup<>
          2
        )
        %span.text-danger *
      .col-8= assessment_f.number_field :property_exclusive_area, step: "0.001", class: 'form-control'

    %label.row.mt-3.property-land-area
      .col-4
        土地面積(m
        %sup<>
          2
        )
        %span.text-danger *
      .col-8= assessment_f.number_field :property_land_area, step: "0.001", class: 'form-control'

    %label.row.mt-3.property-building-area
      .col-4
        建物面積(m
        %sup<>
          2
        )
        %span.text-danger *
      .col-8= assessment_f.number_field :property_building_area, step: "0.001", class: 'form-control'

    %label.row.mt-3
      .col-4
        間取り
        %span.text-danger *
      .col-8= assessment_f.select :property_room_plan, Assessment.property_room_plans_i18n.invert, {}, class: 'form-select', required: true

    %label.row.mt-3
      .col-4
        竣工年
        %span.text-danger *
      .col-8= assessment_f.number_field :property_constructed_year, class: 'form-control', placeholder: '1925 から 2016 の間で入力してください', required: true
    
    .mt-4.d-flex.justify-content-center
      = f.submit "査定依頼する", class: "btn btn-blue text-center w-auto btn--link"

rails/app/views/assessments/success.html.haml
- content_for(:breadcrumbs) do
  = render 'application/breadcrumbs', args: { city: @branch.city, branch: @branch }
- content_for :title, 'お問い合わせありがとうございました'
- content_for(:noindex, true)

%h1.text-center
  お問い合わせありがとうございました
%p
  査定依頼ありがとうございます。
  %br
  不動産会社からのご連絡をお待ちください。