rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount KomachiHeartbeat::Engine => '/ops'

  root 'homes#show'

  resources :branches, only: %i[show] do
    resources :assessments, only: %i[new create] do
      get :success, on: :collection
    end
  end
  resources :sale_reviews, only: %i[show]
  resources :cities, only: %i[show]
end

rails/app/models/city.rb
# frozen_string_literal: true

require 'csv'

class City < ApplicationRecord
  belongs_to :prefecture
  has_many :branches, dependent: :destroy
  has_many :branch_city_assessables, dependent: :destroy
  has_many :assessor_branches, through: :branch_city_assessables, source: :branch
  has_many :sale_reviews, dependent: :destroy # この市の物件に対する口コミ
  has_many :raw_sale_reviews, dependent: :destroy

  def prefecture_city_name
    prefecture.name + name
  end

  def prefecture_city_name_with_space
    "#{prefecture.name} #{name}"
  end

  def self.create_cities_from_csv(path)
    data = CSV.read(path)[1..]
    data.each_with_index do |row, idx|
      city = find_or_initialize_by(id: row[0])
      city.assign_attributes(
        prefecture_id: row[1],
        name: row[2],
        name_yomi: row[3]
      )
      city.save!

      # 100行ごとに出力
      Logger.new($stdout).debug "Line #{idx} OK" if (idx % 100).zero?
    end
  end
end

rails/app/controllers/cities_controller.rb
# frozen_string_literal: true

class CitiesController < ApplicationController
  def show
    @city = City.find_by(id: params[:id])
    @branches = @city.assessor_branches.page(params[:page])
  end
end

rails/app/views/cities/show.html.haml
- content_for(:breadcrumbs) do
  = render 'application/breadcrumbs', args: { city: @city }
- content_for(:title, "#{@city.prefecture_city_name}の不動産会社")
- content_for(:description, "#{@city.prefecture_city_name}の不動産会社一覧をご覧いただけるページです。#{@city.prefecture_city_name}にはどんな不動産会社の情報や評判・口コミをご覧いただけます。複数の不動産会社の口コミを比較することで、あなたの物件をまかせにぴったりの不動産会社を選びましょう。")
- content_for(:meta_keywords, "#{@city.prefecture_city_name} 不動産会社")

- if @city.assessor_branches.empty?
  - content_for(:noindex, true)

%h1.text-center #{@city.prefecture.name} / #{@city.name}の不動産会社

- if @branches.empty?
  %h2.h5.text-danger.ms-3.mt-4 この地域を査定可能な不動産会社は存在しません。
.my-5.centered-content
  - @branches.each do |branch|
    = link_to branch_path(id: branch.id), class: "link-card" do
      .card.mb-3
        .card-body
          .row 
            .col-3.card-title
              %h2.h6.mb-0.fw-bold= branch.company_branch_name
              %div ★ #{number_with_precision(branch.avg_satisfactions, precision: 1)}
            %p.col-9
              営業時間：#{branch.business_hours}
              %br
              定休日：#{branch.regular_holiday}
              %br
              住所：#{branch.address}
          .row
            .col-3 会社の決め手：
            .col-9
              - if branch.sale_reviews.any?
                %p.truncate-text-at-line-3 #{branch.sale_reviews.order(created_at: :desc).first.decision_factor}
  %div= paginate @branches

  .prefecture.mt-5
    = render 'prefectures/cities', prefecture: @city.prefecture